name: pipeline1

on:
  push:
    branches:
      - main

jobs:
  run-python-code:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v7 
      
      - name: print python versio
        run: python --version

      - name: run python program
        run: python welcome.py
