name: ETL Pipeline

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job1"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job1"
  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job1"
  job4:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job1"
  job5:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job1"
  job6:
    needs: [job4, job5]
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job1"

